version: '2'
services:
  web:
    image: ${WEB_IMAGE}
    env_file:
      - ./target/${TARGET_ENV}/web.env
      - ./target/${TARGET_ENV}/db.env
    volumes:
      - ${WEB_VOLUME}:${WEB_IMAGE_VOLUME}
      # dev option
      # - ${SRC_CODE}:${IMG_SRC}
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    image: ${DB_IMAGE}
    env_file:
      - ./target/${TARGET_ENV}/db.env
    volumes:
      - ${DB_VOLUME}:${DB_IMAGE_VOLUME}
  ngx:
    image: ${NGX_IMAGE}
    ports:
      - "${NGX_HTTP_PORT}:80"
      - "${NGX_HTTPS_PORT}:443"
    links:
      - web
    volumes:
      - ./target/${TARGET_ENV}/nginx.conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - web:ro
  redis:
    image: ${REDIS_IMAGE}
